// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYUqoYu9pvoJW8MFLX1p2D1c7t6oZhGZs',
    appId: '1:520500520296:web:7b83a43472a92a6ca0a2dd',
    messagingSenderId: '520500520296',
    projectId: 'air-travel-5c4bb',
    authDomain: 'air-travel-5c4bb.firebaseapp.com',
    storageBucket: 'air-travel-5c4bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZesVCdorK__z3D3aBhTjV05gKLSvACQc',
    appId: '1:520500520296:android:57f39ba3afbce811a0a2dd',
    messagingSenderId: '520500520296',
    projectId: 'air-travel-5c4bb',
    storageBucket: 'air-travel-5c4bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TOQN9_QBDv039UhJGs6bOMBBs8bYjXY',
    appId: '1:520500520296:ios:d5d0e68ae4e571d0a0a2dd',
    messagingSenderId: '520500520296',
    projectId: 'air-travel-5c4bb',
    storageBucket: 'air-travel-5c4bb.firebasestorage.app',
    iosBundleId: 'com.example.ticketPlaneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TOQN9_QBDv039UhJGs6bOMBBs8bYjXY',
    appId: '1:520500520296:ios:d5d0e68ae4e571d0a0a2dd',
    messagingSenderId: '520500520296',
    projectId: 'air-travel-5c4bb',
    storageBucket: 'air-travel-5c4bb.firebasestorage.app',
    iosBundleId: 'com.example.ticketPlaneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYUqoYu9pvoJW8MFLX1p2D1c7t6oZhGZs',
    appId: '1:520500520296:web:aa66c1fcd6d3cacca0a2dd',
    messagingSenderId: '520500520296',
    projectId: 'air-travel-5c4bb',
    authDomain: 'air-travel-5c4bb.firebaseapp.com',
    storageBucket: 'air-travel-5c4bb.firebasestorage.app',
  );
}
